name: deploy-server

on:
  push:
    branches:
    - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Deploy!"
        env:
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_dir: ${{ secrets.DEPLOY_PATH }}
          script: ${{  secrets.DEPLOY_SCRIPT }}
        run: |
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/id_github
          chmod 600 ~/.ssh/id_github
          ssh -p ${remote_port} -i ~/.ssh/id_github -o StrictHostKeyChecking=no ${remote_user}@${remote_host} "cd ${remote_dir} && git pull origin && npm i && pm2 restart ${script}"
          rm ~/.ssh/id_github
